name: "Vincis Terraform Init"
description: "Terraform init to support multiple cloud providers"

branding:
  icon: power
  color: purple

inputs:
  cloud-provider:
    required: true
    description: "Cloud provider for Terraform state backend. [Azure / S3]"
  backend-storage-name:
    required: true
    description: "Name of backend storage location. [Azure Storage Account Name / S3 Bucket Name]"
  tf-version:
    required: false
    description: "The version of Terraform to use. Defaults to latest."
    default: "latest"

outputs:
  init-outcome:
    description: "Terraform init command outcome"
    value: ${{ steps.init.outcome }}

runs:
  using: "composite"
  steps:
    # Install the specified version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf-version }}

    - name: Terraform Init
      id: init
      shell: bash
      run: |
        case "${{ inputs.cloud-provider }}" in
          Azure)
            terraform init -reconfigure \
              -backend-config="storage_account_name=${{ inputs.backend-storage-name }}"
            ;;
          S3)
            export TF_LOG=debug && export GODEBUG=http2client=0 && terraform init -reconfigure \
              -backend-config="bucket=${{ inputs.backend-storage-name }}"
            ;;
          *)
            echo "Unsupported cloud provider: ${{ inputs.cloud-provider }}"
            exit 1
            ;;
        esac
